version: "3.1"
services:
  orion:
    image: fiware/orion:latest
    depends_on:
      - mongo-db
    networks:
        - fiware
    ports:
        - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  fiware:
