version: "3.8"

services:
  
  mongo-db:
    image: mongo:4.4 #Check https://docs.mongodb.com/manual/release-notes/
    hostname: mongo-db
    container_name: "mongo-db"
    restart: always
    networks:
        - fiware
    volumes:
      - mongo-db:/data/db
          
  orion:
    #Sometimes the newest builds fail. Hence, we fixed a stable version that
    #probably will be updated once in a while
    image: fiware/orion:3.2.0
    hostname: orion
    restart: always
    container_name: "orion"
    depends_on:
        - mongo-db
    networks:
        - fiware
    ports:
       - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG -noCache -logForHumans
         

  iot-agent:
    image: fiware/iotagent-json:1.19.0
    hostname: iot-agent
    container_name: "iot-agent"
    restart: always
    depends_on:
      - mongo-db
    ports:
      - "4041:4041"
    networks:
      - fiware
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_TIMESTAMP=true
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_AUTOCAST=false
      - IOTA_EXPLICIT_ATTRS=true
      - IOTA_MONGO_HOST=mongo-db
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagentjson
      - IOTA_PROVIDER_URL=http://iot-agent:4041
      - IOTA_DEFAULT_RESOURCE=/iot/json
      - IOTA_HTTP_PORT=7896
      - IOTA_MQTT_HOST=mosquitto
      - IOTA_MQTT_PORT=1883
      - IOTA_MQTT_PROTOCOL=mqtt
      - IOTA_MQTT_KEEPALIVE=60
    
  mosquitto:
    image: eclipse-mosquitto:2.0.10
    restart: always
    hostname: mosquitto
    container_name: mosquitto
    ports: 
        - "1883:1883"
    networks:
        - fiware
    volumes:
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  quantumleap:
    image: orchestracities/quantumleap:0.8.1
    hostname: quantumleap
    container_name: quantumleap
    depends_on:
      - orion
      - crate
    networks:
      - fiware
    ports:
      - "8668:8668"
    environment:
      - CRATE_HOST=crate
      
  crate:
    image: crate:4.5
    restart: always
    hostname: crate
    container_name: crate
    networks:
        - fiware
    ports:
      - "4200:4200"
    volumes:
      - crate:/data
    environment: 
      - TZ=Europe/Berlin
      - CRATE_HEAP_SIZE=2g

  grafana:
    image: grafana/grafana
    restart: always
    container_name: grafana
    depends_on:
      - crate
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,grafana-simple-json-datasource
      - TZ=Europe/Berlin
    volumes:
      - "grafana:/var/lib/grafana"
    ports:
      - "3001:3000"
    networks:
      - fiware


volumes:
  mongo-db:
    name: mongodb
  crate:
    name: crate
  grafana:
    name: grafana

networks:
  fiware:
    name: fiware
