version: '3'
services:
  grafana:
    image: grafana/grafana
    depends_on:
      - crate
    environment:
      - GF_INSTALL_PLUGINS=crate-datasource,grafana-clock-panel,grafana-worldmap-panel
    ports:
      - "3001:3000"
    networks:
      - fiware

networks:
  fiware:

