version: "3.1"
services:
    iot-agent:
        image: fiware/iotagent-ul:latest
        hostname: iot-agent
        container_name: fiware-iot-agent
        depends_on:
            - mongo-db
        networks:
            - fiware
        ports:
            - "4041:4041"
        environment:
            - "IOTA_CB_HOST=orion"
            - "IOTA_CB_PORT=1026"
            - "IOTA_NORTH_PORT=4041"
            - "IOTA_REGISTRY_TYPE=mongodb"
            - "IOTA_LOG_LEVEL=DEBUG"
            - "IOTA_TIMESTAMP=true"
            - "IOTA_MONGO_HOST=mongo-db"
            - "IOTA_MONGO_PORT=27017"
            - "IOTA_MONGO_DB=iotagentul"
            - "IOTA_PROVIDER_URL=http://iot-agent:4041"
            - "IOTA_MQTT_HOST=mosquitto"
            - "IOTA_MQTT_PORT=1883"

    networks:
      fiware:
